# Generated by Django 6.0.1 on 2026-01-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_horario_dia_semana'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='sala',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
