# Generated by Django 6.0.1 on 2026-01-27 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='disciplina',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='ano',
        ),
    ]
