# Generated by Django 6.0.1 on 2026-01-27 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_professor_disciplina_remove_turma_ano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='disciplina',
        ),
        migrations.DeleteModel(
            name='Disciplina',
        ),
    ]
