# Generated by Django 6.0.1 on 2026-01-27 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_disciplina_functionality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracaoTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aulas_por_semana', models.PositiveIntegerField(default=5)),
                ('aulas_por_dia_max', models.PositiveIntegerField(default=1)),
                ('preferencias_dias', models.JSONField(blank=True, default=list)),
                ('disposicao_aulas', models.CharField(choices=[('separadas', 'Aulas Separadas'), ('duplicadas', 'Aulas Duplicadas'), ('uma_por_dia', 'Uma Aula por Dia'), ('concentradas', 'Aulas Concentradass')], default='separadas', max_length=20)),
                ('turma', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.turma')),
            ],
        ),
        migrations.CreateModel(
            name='RestricaoHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('bloqueio', 'Bloqueio de Horário'), ('preferencia', 'Preferência de Horário'), ('simultaneo', 'Aulas Simultâneas'), ('local', 'Restrição de Local')], max_length=20)),
                ('dia_semana', models.CharField(blank=True, choices=[('Segunda', 'Segunda-feira'), ('Terça', 'Terça-feira'), ('Quarta', 'Quarta-feira'), ('Quinta', 'Quinta-feira'), ('Sexta', 'Sexta-feira')], max_length=10, null=True)),
                ('horario_inicio', models.TimeField(blank=True, null=True)),
                ('horario_fim', models.TimeField(blank=True, null=True)),
                ('descricao', models.TextField()),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.professor')),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.turma')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.unidade')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.unidade')),
            ],
        ),
        migrations.CreateModel(
            name='DisponibilidadeProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('Segunda', 'Segunda-feira'), ('Terça', 'Terça-feira'), ('Quarta', 'Quarta-feira'), ('Quinta', 'Quinta-feira'), ('Sexta', 'Sexta-feira')], max_length=10)),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.professor')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.unidade')),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracaoProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aulas_diarias_max', models.PositiveIntegerField(default=6)),
                ('aulas_semanais_max', models.PositiveIntegerField(default=30)),
                ('dias_trabalho_max', models.PositiveIntegerField(default=5)),
                ('prioridade_minimizacao', models.CharField(choices=[('dias_trabalho', 'Minimizar Dias de Trabalho'), ('vagas', 'Minimizar Vagas'), ('equilibrado', 'Equilibrado')], default='equilibrado', max_length=20)),
                ('professor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.professor')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.unidade')),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('reuniao', 'Reunião'), ('formacao', 'Formação'), ('conselho', 'Conselho de Classe'), ('outro', 'Outro')], default='reuniao', max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('data', models.DateField()),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('sala', models.CharField(blank=True, max_length=50)),
                ('professores', models.ManyToManyField(blank=True, to='core.professor')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.unidade')),
            ],
        ),
    ]
