from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='home'), name='logout'),
    path('', views.home, name='home'),
    path('turmas/', views.lista_turmas, name='lista_turmas'),
    path('turmas/cadastrar/', views.cadastrar_turma, name='cadastrar_turma'),
    path('turmas/<int:pk>/editar/', views.editar_turma, name='editar_turma'),
    path('turmas/<int:pk>/excluir/', views.excluir_turma, name='excluir_turma'),
    path('professores/', views.lista_professores, name='lista_professores'),
    path('professores/cadastrar/', views.cadastrar_professor, name='cadastrar_professor'),
    path('professores/<int:pk>/editar/', views.editar_professor, name='editar_professor'),
    path('professores/<int:pk>/excluir/', views.excluir_professor, name='excluir_professor'),
    path('horarios/', views.lista_horarios, name='lista_horarios'),
    path('horarios/cadastrar/', views.cadastrar_horario, name='cadastrar_horario'),
    path('horarios/<int:pk>/editar/', views.editar_horario, name='editar_horario'),
    path('horarios/<int:pk>/excluir/', views.excluir_horario, name='excluir_horario'),
    path('horarios/exportar_pdf/', views.exportar_horarios_pdf_moderno, name='exportar_horarios_pdf'),
    path('horarios/otimizar/', views.otimizar_horarios, name='otimizar_horarios'),
    path('configuracoes/professor/', views.configuracoes_professor, name='configuracoes_professor'),
    path('configuracoes/professor/<int:pk>/editar/', views.editar_configuracao_professor, name='editar_configuracao_professor'),
    path('configuracoes/turma/', views.configuracoes_turma, name='configuracoes_turma'),
    path('configuracoes/turma/<int:pk>/editar/', views.editar_configuracao_turma, name='editar_configuracao_turma'),
    path('disponibilidades/', views.lista_disponibilidades, name='lista_disponibilidades'),
    path('disponibilidades/cadastrar/', views.cadastrar_disponibilidade, name='cadastrar_disponibilidade'),
    path('disponibilidades/<int:pk>/editar/', views.editar_disponibilidade, name='editar_disponibilidade'),
    path('disponibilidades/<int:pk>/excluir/', views.excluir_disponibilidade, name='excluir_disponibilidade'),
    path('atividades-extras/', views.lista_atividades_extras, name='lista_atividades_extras'),
    path('atividades-extras/cadastrar/', views.cadastrar_atividade_extra, name='cadastrar_atividade_extra'),
    path('atividades-extras/<int:pk>/editar/', views.editar_atividade_extra, name='editar_atividade_extra'),
    path('atividades-extras/<int:pk>/excluir/', views.excluir_atividade_extra, name='excluir_atividade_extra'),
    path('restricoes/', views.lista_restricoes, name='lista_restricoes'),
    path('restricoes/cadastrar/', views.cadastrar_restricao, name='cadastrar_restricao'),
    path('restricoes/<int:pk>/editar/', views.editar_restricao, name='editar_restricao'),
    path('restricoes/<int:pk>/excluir/', views.excluir_restricao, name='excluir_restricao'),
    path('associacao-professor-dia/', views.associacao_professor_dia, name='associacao_professor_dia'),
]
